### ISSUE TITLE
Could not invoke constructor for DoseCalculationByMedAndAge[0]

### ISSUE THREAD

**Issue by aymanapatel** [weaverj/erserver#1]
When `Test` is issued, it throws an exception `Could not invoke constructor for DoseCalculationByMedAndAge[0]` . Subsequently, all cells give the `The instance *.* does not exist` exception.

**Comment by weaverj** [comment]
Hi Ayman - thanks!  Should be fixed now.  It was a fitnesse page used for importing the class files that was wrong.  Fix is committed now.  I think I renames the package names at some point and broke that fitnesse import when I did.
